# Set this parameter to use a specific arm on your system    --> 
# serial_number: PJ00000001030703130

# Joint speed limit for joints 1, 2, 3
jointSpeedLimitParameter1: 10

# Joint speed limit for joints 4, 5, 6
jointSpeedLimitParameter2: 20

# payload: [COM COMx COMy COMz]
payload: [0.6, 0.0, 0.0, 0]

connection_type: USB #Ethernet

# Ethernet connection parameters
ethernet: {
  local_machine_IP: 10.66.171.24,
  subnet_mask: 255.255.255.0,
  local_cmd_port: 25000,
  local_broadcast_port: 25025
}

# Gravity parameters based on arm mounting position
is_arm_vertical: true

#Torque control parameters
#Do not change these parameters unless you want to change torque control behavior
torque_parameters: {
      publish_torque_with_gravity_compensation: true,
      use_estimated_COM_parameters: false,
    # if torque min/max sepecified, all min/max values need to be specified
    #  torque_min: [80, 80, 80, 80, 80, 80, 80],
    #  torque_max: [90, 90, 90, 90, 90, 90, 90],
    # Decides velocity threshold at which robot switches torque to position control (between 0 and 1)
    # safety_factor: 1,
    # COM parameters
    # order [m1,m2,...,m7,x1,x2,...,x7,y1,y2,...y7,z1,z2,...z7]
    # com_parameters: [0,0,0,0,0,0,0, 0,0,0,0,0,0,0, 0,0,0,0,0,0,0, 0,0,0,0,0,0,0]
      com_parametesr: [-0.00951158,-1.51002,-0.0280768,-0.0521875,0.00303779,-0.654485,0.0022891,-0.00324771,0.0107416,-0.227445,-9.48868e-05,-0.00834449,0.354482,-0.0499593,-0.157997,-0.0895242,-0.0434689,-0.0799657,-0.0397365]
 
}
